// [[path]].ts
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
import type { ServerBuild } from '@remix-run/cloudflare';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by remix vite:build
// eslint-disable-next-line import/no-unresolved
import * as build from '../build/server/index.js';

export const onRequest = createPagesFunctionHandler({
	// Fix the type of the server build file
	build: build as unknown as ServerBuild,
});
